"""Index generation for the memory store.

`build_descriptions()` emits a flat, sorted catalog (`_descriptions.md`) derived
purely from each memory's frontmatter `description`. It is a BUILD ARTIFACT —
never hand-edited (same spirit as the rules `fallback_rules.md`). The source of
truth stays the frontmatter in each memory file; this is a generated cache that
gives a one-line-per-memory overview plus stable line numbers a lean `MEMORY.md`
hot-index can reference (read directly to line N → the description, zero waste).

The grouped `MEMORY.md` hot-TOC generation is added once the bundling map exists
— that grouping (which package a memory lives in) is human-curated, not
auto-derivable from frontmatter, so it is NOT regenerated destructively here.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from mcp_context_toolkit.memory import MemoryEngine

_HEADER = [
    "# Memory Descriptions (auto-generated — DO NOT EDIT)",
    "",
    "Flat catalog: one line per memory. Source of truth = each file's frontmatter",
    "`description`. Regenerated by build_descriptions() (e.g. on a consolidation run).",
    "Line numbers are stable per generation — a lean MEMORY.md references them.",
    "",
]

DESCRIPTIONS_FILENAME = "_descriptions.md"


def build_descriptions(
    memory_dir: str | Path, engine: Optional[MemoryEngine] = None
) -> dict:
    """Build the flat descriptions catalog.

    Returns ``{content, line_index: {name: 1-based-line}, count}``. Deterministic
    (sorted by type then name) so regeneration is byte-stable across machines —
    that stability is what makes the line-number references safe to commit.
    """
    eng = engine or MemoryEngine.from_directory(memory_dir)
    mems = sorted(eng.memories, key=lambda m: (m.type, m.name))

    lines = list(_HEADER)
    line_index: dict[str, int] = {}
    for m in mems:
        desc = " ".join((m.description or "").split())  # collapse whitespace/newlines
        fname = Path(m.source_path).name if m.source_path else f"{m.name}.md"
        # Inbound edges (who links here). Sorted → byte-stable, safe to commit.
        cited = eng.backlinks(m.name)
        suffix = f"  ← cited by: {', '.join(cited)}" if cited else ""
        lines.append(f"- **{m.name}** ({m.type}) — {desc} → {fname}{suffix}")
        line_index[m.name] = len(lines)  # 1-based line number of this entry

    return {
        "content": "\n".join(lines) + "\n",
        "line_index": line_index,
        "count": len(mems),
    }


_TIER_ORDER = ["core", "user", "project"]


def build_memory_md(packages: list[dict], title: str = "Memory — Index") -> str:
    """Lean hot-index TOC: ONE line per PACKAGE, grouped by tier. The top of the
    3-tier read model (hot → `_descriptions.md` catalog → package file). Tiny:
    ~70 package lines regardless of how many memories the packages hold."""
    tiers: dict[str, list[dict]] = {}
    for p in packages:
        tiers.setdefault(p.get("tier", "project"), []).append(p)
    lines = [
        f"# {title} (auto-generated — DO NOT EDIT)",
        "",
        "Hot index: packages by tier. Find a specific memory via `recall` or the flat",
        "catalog `_descriptions.md`. Regenerated by the context-toolkit indexer.",
        "",
    ]
    for tier in _TIER_ORDER + [t for t in sorted(tiers) if t not in _TIER_ORDER]:
        plist = sorted(tiers.get(tier, []), key=lambda x: x["file"])
        if not plist:
            continue
        lines.append(f"## {tier}")
        for p in plist:
            t = p.get("title") or Path(p["file"]).stem
            lines.append(f"- [{t}]({p['file']}) — {len(p['members'])} memories")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_member_catalog(packages: list[dict], engine: MemoryEngine) -> dict:
    """Flat catalog mapping every MEMBER (slug) → its package, with the member's
    description. Built from the ORIGINAL atomic store (run BEFORE bundling).
    Returns {content, line_index, count}. The middle layer of the read model."""
    by_slug = {
        (Path(m.source_path).stem if m.source_path else m.name): m
        for m in engine.memories
    }
    lines = [
        "# Memory Member Catalog (auto-generated — DO NOT EDIT)",
        "",
        "One line per memory → its package. Find a specific memory by name here,",
        "then read its package. Regenerated by the context-toolkit indexer.",
        "",
    ]
    line_index: dict[str, int] = {}
    for pkg in sorted(packages, key=lambda x: x["file"]):
        for slug in pkg["members"]:
            m = by_slug.get(slug)
            desc = " ".join((m.description or "").split()) if m else ""
            lines.append(f"- **{slug}** — {desc} → {pkg['file']}")
            line_index[slug] = len(lines)
    return {
        "content": "\n".join(lines) + "\n",
        "line_index": line_index,
        "count": len(line_index),
    }


def write_descriptions(
    memory_dir: str | Path, engine: Optional[MemoryEngine] = None
) -> dict:
    """Generate + write `_descriptions.md` into the memory dir.

    Returns ``{path, count, line_index}``. The `_`-prefix keeps the artifact out
    of ``iter_files`` (never re-parsed as a memory)."""
    result = build_descriptions(memory_dir, engine=engine)
    target = Path(memory_dir) / DESCRIPTIONS_FILENAME
    target.write_text(result["content"], encoding="utf-8")
    return {
        "path": str(target),
        "count": result["count"],
        "line_index": result["line_index"],
    }
